name: CD Pipeline

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Build Go binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o hse_backend ./cmd/main.go
      
      - name: Prepare files for deploy
        run: |
          mkdir deploy_backend
          cp hse_backend deploy_backend/
          cp docker-compose.yml deploy_backend/
          mkdir -p deploy_backend/internal/db/migrations
          cp internal/db/migrations/initial_up.sql deploy_backend/internal/db/migrations/

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          port: 22
          source: "deploy_backend/*"
          target: "/opt/hse-backend"
          strip_components: 1

      - name: Restart Backend Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            sudo systemctl restart hse-backend
